ServiceMaps:
 serviceName: Trade License
 version: 1.0.0
 mappings:
  - topic: save-tl-tradelicense
    indexes:
    - name: tlindex-v1
      type: tradelicenses
      id: $.id, $.tenantId
      isBulk: true
      jsonPath: $.Licenses
      
  - topic: update-tl-tradelicense
    indexes:
    - name: tlindex-v1
      type: tradelicenses
      id: $.id, $.tenantId
      isBulk: true
      jsonPath: $.Licenses
